### ISSUE TITLE
Attempting to back up to a remote destination generates exception

### ISSUE THREAD

**Issue by glennlagasse** [seanh/snapshotter#37]
Trying to execute a snapshot to a remote destination fails with the following exception:

`./.local/bin/snapshotter --dry-run /home/glagasse glagasse@192.168.1.151:/tank/timemachine/praetorian
Traceback (most recent call last):
  File "./.local/bin/snapshotter", line 9, in <module>
    load_entry_point('snapshotter==1.0.3', 'console_scripts', 'snapshotter')()
  File "/home/glagasse/.local/lib/python2.7/site-packages/snapshotter/snapshotter.py", line 480, in main
    snapshot(*_parse_cli())
  File "/home/glagasse/.local/lib/python2.7/site-packages/snapshotter/snapshotter.py", line 400, in snapshot
    while len(_ls_snapshots(dest)) >= max_snapshots:
  File "/home/glagasse/.local/lib/python2.7/site-packages/snapshotter/snapshotter.py", line 303, in _ls_snapshots
    snapshots = [os.path.join(dest, d) for d in os.listdir(dest)
OSError: [Errno 2] No such file or directory: 'glagasse@192.168.1.151:/tank/timemachine/praetorian'
`

This happens because snapshotter is trying to find the number of remote snapshots in the remote destination using the host machine. 
Lines 400-402 is where _ls_snapshots(dest) is called and inside _ls_snapshots it is trying to do a listdir (on the host machine) of the destination which naturally won't exist.

**Comment by seanh** [comment]
Thanks @glennlagasse, I'll look into this when I get a chance. It should be running `ls` with `ssh` for remote servers.
